# Generated by Django 5.1 on 2024-09-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artist_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
