# Generated by Django 5.1 on 2024-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_artistprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='profile',
            field=models.ImageField(default='default-images/artist-profile.png', upload_to=''),
        ),
    ]
